# Generated by Django 3.2.3 on 2021-06-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calisanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı Soyadı')),
                ('tc', models.CharField(max_length=11, verbose_name='TC Kimlik No')),
                ('isgecmisi', models.TextField(verbose_name='Daha önce çalıştığınız yerler')),
                ('iskazaları', models.TextField(verbose_name='Geçirmiş olduğunuz iş kazaları')),
                ('engel', models.TextField(verbose_name='Engeliniz')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
        ),
    ]
