# Generated by Django 3.2.3 on 2021-06-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210602_0540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kayitlar',
        ),
    ]
