# Generated by Django 3.2.3 on 2021-05-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takim',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='takim',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='takim',
            name='description',
            field=models.TextField(verbose_name='Üye Açıklaması'),
        ),
        migrations.AlterField(
            model_name='takim',
            name='image',
            field=models.CharField(max_length=50, verbose_name='Üye Resmi'),
        ),
        migrations.AlterField(
            model_name='takim',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ekip Üyesi'),
        ),
    ]
